package com.tempura17.model;

public enum Especialidad {
    ALERGOLOGIA, ANESTESIOLOGIA, CARDIOLOGIA, ENDOCRINOLOGIA, EPIDEMIOLOGIA, 
    HEMATOLOGIA, MEDICINA_DE_EMERGENCIA, MEDICINA_INTERNA, MEDICINA_GENERAL, NEUMOLOGIA, NEUROLOGIA, ONCOLOGIA, PEDIATRIA, PSIQUIATRIA

    
}
